export const INPUTCHANGED = 'INPUTCHANGED'
export const SEARCHİNGUSER = 'SEARCHİNGUSER'
export const SEARCHİNGUSERSUCCESS = 'SEARCHİNGUSERSUCCESS'
export const SEARCHİNGUSERFAIL = 'SEARCHİNGUSERFAIL'
